# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app-frontend
  labels:
    app: movie-app-frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-app-frontend

  template:
    metadata:
      name: movie-app-frontend
      labels:
        app: movie-app-frontend

    spec:
      containers:
        - name: movie-app-frontend
          image: gcr.io/kp-test-project-2/movie_app_frontend
          imagePullPolicy: Always
          ports:
            -containerPort: 80

---
# service
apiVersion: v1
kind: Service
metadata:
  name: movie-app-frontend
spec:
  selector:
    app: movie-app-frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
